### ISSUE TITLE
Voice Over Product Page/Checkout Form

### ISSUE THREAD

**Issue by Sebby-T** [Pinestorm/ecommerce-pattern-library#10]
The header and footer need aria labels on their links to describe where they are bringing the user. The product detail section reads just fine and there isn't an issue there. 

The item cards need an aria-label to describe them as well. 
The review cards also don't read out when focused

The checkout form is pretty well perfect, just a suggestion. The credit card number can just be a text field.

Overall great job on the website!

**Comment by nep2ne** [comment]
Same comments on the home page and product list. The navigation description is great, but you could add more description to the cards. 
Great job!
